export const ActionType = {
    GET_FILMS:"GET_FILMS",
    GET_FILM:"GET_FILM",
    REMOVE_FROM_WISHLIST:"REMOVE_FROM_WISHLIST",
    ADD_IN_WISHLIST:"ADD_IN_WISHLIST",
    GET_RECOMANDATIONS:"GET_RECOMANDATIONS"
}